### PR TITLE
The Licensing.

### PR DESCRIPTION
**Pull request by MostAwesomeDude**
@edunham, as discussed yesterday, please consider and approve this licensing change. It is my opinion that MIT/X11 can be upgraded into Apache 2.0 without disrupting the copyright of the original authors.

### CODE REVIEW

**Comment by edunham** [comment]
@MostAwesomeDude, please clarify why retroactively assigning copyright to Google, Inc. is necessary. 

It was my understanding that the changes made during your time at Google were accepted into the Baskerville project only because they were made on your free time and without the use of any Google resources, and would thus not require reassignment of copyright. 

Other than requiring a better explanation for the `Copyright (C) 2014 Google Inc. All rights reserved.` part, the switch from MIT/X11 to Apache 2.0 is fine by me. Remember that GitHub's workflow will automatically add any additional commits to the `licensing` branch into this PR.

**Comment by MostAwesomeDude** [comment]
It was, until Tuesday (May 22), my understanding as well. However, Google's opinion is different from mine, and I am politely deferring to their policy for now. If this is unacceptable, we can probably discuss destroying the relevant commits by `filter-branch` or other mechanism. The first such commit is 39a7ac2f.

Whatever decision we reach here would be the same decision applied to Bravo, since that repository is in the same condition; the first such commit in Bravo is bravoserver/bravo@07e16917.

**Comment by edunham** [comment]
I hope that deleting the commits isn't necessary. If the copyright assignment is a temporary measure to make sure no code which might end up belonging to Google gets misused, I'd strongly prefer to add a note to the README and LICENSE files explaining that Baskerville/Bravo code should not be reused until the legal ambiguity gets sorted out. 

My main qualm with the copyright assignment is that, as I understand it, such a transfer of rights is permanent. If I understand incorrectly and the actual plan is only to prevent misuse for a limited period of time until a more final conclusion can be reached, let's discuss the best way to proceed. I would strongly prefer to avoid rewriting history due to the inconvenience which it would cause other contributors, especially on Bravo. 

Please explain why Google holds the opinion that it suddenly retroactively owns code written on your own time, so that I can make a fully informed decision about what the Baskerville and Bravo projects should do with that code.

**Comment by MostAwesomeDude** [comment]
All affected commits have been cleared and are no longer contentious. Apologies for the confusion.

**Pull request closed without merging**
